//! Hook installer for `.config/wt.toml` (M4).
//!
//! Worktrunk reads hook configuration from `<repo>/.config/wt.toml`.
//! On a fresh repo open, we offer to install gitsu's recommended
//! `post-start` hook that runs `wt step copy-ignored` — the ergonomic
//! glue that brings `.env`, `node_modules/`, `target/`, etc. into
//! new worktrees (and the recopy button in the per-worktree card).
//!
//! The installer is intentionally non-destructive: if `.config/wt.toml`
//! already exists, we add a `[post-start]` section only if not
//! present, never clobbering user hooks.

use std::path::Path;

use crate::error::{Error, Result};
use crate::ipc::HookConfigSnapshot;

const HOOK_LINE: &str = r#"copy = "wt step copy-ignored""#;

const HOOK_BLOCK: &str = r#"# Generated by gitsu. Edit / remove in the Hooks manager.
# Docs: https://worktrunk.dev/hook/

[post-start]
"#;

const DEFAULT_WORKTREEINCLUDE: &str = r#"# Generated by gitsu. This file controls which gitignored
# files `wt step copy-ignored` carries into new worktrees.
# See https://worktrunk.dev/step/#wt-step-copy-ignored

# Environment files
.env
.env.local
.env.*.local

# Common dependency / build caches
node_modules/
target/
.next/
.nuxt/
.output/
dist/
build/
.venv/
venv/
__pycache__/
.pyo/
.pyd

# Generated assets (size > git's friendliness)
*.log
.DS_Store
"#;

/// Snapshot the current hook configuration. Used by the Hooks manager
/// UI to show what's installed.
pub fn snapshot(repo: &Path) -> Result<HookConfigSnapshot> {
    let config_path = repo.join(".config").join("wt.toml");
    let installed = config_path.exists();
    let has_post_start_copy_ignored = if installed {
        match std::fs::read_to_string(&config_path) {
            Ok(s) => has_post_start_copy_ignored(&s),
            Err(_) => false,
        }
    } else {
        false
    };

    let include_path = repo.join(".worktreeinclude");
    let (worktreeinclude_path, worktreeinclude_contents) = if include_path.exists() {
        let contents = std::fs::read_to_string(&include_path).ok();
        (Some(include_path.display().to_string()), contents)
    } else {
        (None, None)
    };

    Ok(HookConfigSnapshot {
        installed,
        has_post_start_copy_ignored,
        config_path: config_path.display().to_string(),
        worktreeinclude_path,
        worktreeinclude_contents,
    })
}

/// Result of [`install`]. Carries the snapshot the caller returns
/// to the UI plus a flag telling the caller whether the hook block
/// was newly written (vs. already present). The IPC layer uses that
/// flag to decide whether to pre-approve the command via
/// `wt config approvals add` — we only do that when the user just
/// consented to installing it, never when it was already there.
pub struct InstallResult {
    pub snapshot: HookConfigSnapshot,
    /// `true` if the post-start block was written by this call.
    pub newly_installed: bool,
}

/// Install gitsu's recommended post-start hook. Idempotent: if the
/// hook is already installed, returns the existing snapshot. If the
/// config file exists but the hook is missing, appends the section.
/// If it doesn't exist, creates a fresh file.
pub fn install(repo: &Path, with_worktreeinclude: bool) -> Result<InstallResult> {
    let config_path = repo.join(".config").join("wt.toml");
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| {
            Error::Internal(format!("create .config: {e}"))
        })?;
    }

    let needs_append = if config_path.exists() {
        let existing = std::fs::read_to_string(&config_path)
            .map_err(|e| Error::Internal(format!("read .config/wt.toml: {e}")))?;
        !has_post_start_copy_ignored(&existing)
    } else {
        true
    };

    if needs_append {
        let mut content = if config_path.exists() {
            let mut s = std::fs::read_to_string(&config_path)
                .map_err(|e| Error::Internal(format!("read .config/wt.toml: {e}")))?;
            if !s.ends_with('\n') {
                s.push('\n');
            }
            s.push('\n');
            s
        } else {
            String::new()
        };
        content.push_str(HOOK_BLOCK);
        content.push_str(HOOK_LINE);
        content.push('\n');
        std::fs::write(&config_path, content)
            .map_err(|e| Error::Internal(format!("write .config/wt.toml: {e}")))?;
    }

    if with_worktreeinclude {
        let include_path = repo.join(".worktreeinclude");
        if !include_path.exists() {
            std::fs::write(&include_path, DEFAULT_WORKTREEINCLUDE)
                .map_err(|e| Error::Internal(format!("write .worktreeinclude: {e}")))?;
        }
    }

    Ok(InstallResult {
        snapshot: snapshot(repo)?,
        newly_installed: needs_append,
    })
}

/// Remove gitsu's post-start hook from `.config/wt.toml`. If the file
/// is now empty (only contained the gitsu block), delete it.
pub fn uninstall(repo: &Path) -> Result<HookConfigSnapshot> {
    let config_path = repo.join(".config").join("wt.toml");
    if config_path.exists() {
        let s = std::fs::read_to_string(&config_path)
            .map_err(|e| Error::Internal(format!("read: {e}")))?;
        // Remove the gitsu-generated block: the comment header + the
        // [post-start] section + the `copy` line. We do this with a
        // simple heuristic: find the comment marker and remove from
        // there to the next blank line / EOF.
        let cleaned = strip_gitsu_block(&s);
        if cleaned.trim().is_empty() {
            std::fs::remove_file(&config_path)
                .map_err(|e| Error::Internal(format!("remove: {e}")))?;
        } else {
            std::fs::write(&config_path, cleaned)
                .map_err(|e| Error::Internal(format!("write: {e}")))?;
        }
    }
    snapshot(repo)
}

fn has_post_start_copy_ignored(content: &str) -> bool {
    // Heuristic: look for a `[post-start]` section whose body contains
    // `copy = "wt step copy-ignored"`. Simple, good enough.
    let mut in_post_start = false;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            in_post_start = trimmed == "[post-start]";
            continue;
        }
        if in_post_start && trimmed.contains("wt step copy-ignored") {
            return true;
        }
    }
    false
}

fn strip_gitsu_block(content: &str) -> String {
    // Remove lines from "Generated by gitsu" up to (but not including)
    // the next non-gitsu section. We keep the user's content intact.
    let mut out = String::new();
    let mut skipping = false;
    for line in content.lines() {
        if line.contains("Generated by gitsu") {
            skipping = true;
            continue;
        }
        if skipping {
            // Stop skipping at the next user-authored section header
            // (e.g. `[pre-merge]`, `[commit]`, etc.) — but not
            // `[post-start]`, which is gitsu's.
            let trimmed = line.trim();
            if trimmed.starts_with('[') && trimmed != "[post-start]" {
                skipping = false;
            }
        }
        if !skipping {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_gitsu_post_start_block() {
        let s = "[post-start]\ncopy = \"wt step copy-ignored\"\n";
        assert!(has_post_start_copy_ignored(s));
        let s2 = "[pre-commit]\nlint = \"cargo clippy\"\n";
        assert!(!has_post_start_copy_ignored(s2));
    }

    #[test]
    fn strips_gitsu_block() {
        let s = "[pre-commit]\nlint = \"cargo clippy\"\n\n# Generated by gitsu. Edit / remove in the Hooks manager.\n[post-start]\ncopy = \"wt step copy-ignored\"\n";
        let out = strip_gitsu_block(s);
        assert!(out.contains("[pre-commit]"));
        assert!(out.contains("cargo clippy"));
        assert!(!out.contains("Generated by gitsu"));
        assert!(!out.contains("copy-ignored"));
    }
}
